package com.example.mapper;

import com.example.entity.SchedulerJob;
import java.util.List;

public interface SchedulerJobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduler_job
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduler_job
     *
     * @mbggenerated
     */
    int insert(SchedulerJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduler_job
     *
     * @mbggenerated
     */
    SchedulerJob selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduler_job
     *
     * @mbggenerated
     */
    List<SchedulerJob> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduler_job
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SchedulerJob record);
}